server:
  port: 8081

---

spring:
  profiles: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
